# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PhatAndPhresh' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PhatAndPhresh
    pod "Pulsator"
    pod 'Spring', :git => 'https://github.com/MengTo/Spring.git', :branch => 'swift4'
    pod 'NVActivityIndicatorView'
    pod 'JTMaterialTransition', '~> 2.0'
    pod 'Alamofire', '~> 4.5'
    pod 'SwiftyJSON'

  target 'PhatAndPhreshTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PhatAndPhreshUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
